name: Build website
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4 # FIXME: add apt (latex)
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '.github/python/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install TeXLive
        uses: DanySK/setup-texlive-action@0.1.1
      - id: setup-python
        name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: ".github/python/requirements.txt"
      - name: Building notes
        run: make ready
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build website
        uses: actions/jekyll-build-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    if: >
      github.ref == 'refs/heads/main'
      && github.repository == 'UCL-RITS/doctoral-programming-intro'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
